### ISSUE TITLE
Missing a ckpt file 

### ISSUE THREAD

**Issue by DanielAronovich** [SamsungLabs/rome#10]
I am trying to run the example after installing all the dependencies: 
`python3 infer.py --deca DECA --rome data
`

I get the following error:
`Start infer!
creating the FLAME Decoder
please check model path: DECA/data/deca_model.tar
Traceback (most recent call last):
  File "/Users/danielaronovich/repos/face/rome/infer.py", line 218, in <module>
    main(args)
  File "/Users/danielaronovich/repos/face/rome/infer.py", line 194, in main
    infer = Infer(args)
  File "/Users/danielaronovich/repos/face/rome/infer.py", line 51, in __init__
    self.setup_modnet()
  File "/Users/danielaronovich/repos/face/rome/infer.py", line 64, in setup_modnet
    modnet.load_state_dict(torch.load(pretrained_ckpt, map_location='cpu'))
  File "/Users/danielaronovich/opt/miniconda3/envs/experiment/lib/python3.9/site-packages/torch/serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/danielaronovich/opt/miniconda3/envs/experiment/lib/python3.9/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/danielaronovich/opt/miniconda3/envs/experiment/lib/python3.9/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'MODNet/pretrained/modnet_photographic_portrait_matting.ckpt'
`

What am I missing?

**Comment by DanielAronovich** [comment]
found it here:
https://drive.google.com/drive/folders/1umYmlCulvIFNaqPjwod1SayFmSRHziyR
